# packaging_tables.py

STANDARD_BOXES = {  
    "None": {
        "Packaging_Characteristics": "",
        "Cost_per_pcs": 0.00,
        "L": 0,
        "W": 0,
        "H": 0,
        "MT_weight_kg": 0.0,
        "Pcs_Boxes_per_LU": 0,
        "Boxes_per_layer": 0,
    },
    "Cardboard S": {
        "Packaging_Characteristics": "One Way",
        "Cost_per_pcs": 0.83,
        "L": 294,
        "W": 194,
        "H": 137,
        "MT_weight_kg": 0.25,
        "Pcs_Boxes_per_LU": 120,
        "Boxes_per_layer": 20,
    },
    "Cardboard M": {
        "Packaging_Characteristics": "One Way",
        "Cost_per_pcs": 1.64,
        "L": 394,
        "W": 294,
        "H": 137,
        "MT_weight_kg": 0.5,
        "Pcs_Boxes_per_LU": 60,
        "Boxes_per_layer": 10,
    },
    "Cardboard L": {
        "Packaging_Characteristics": "One Way",
        "Cost_per_pcs": 3.86,
        "L": 585,
        "W": 392,
        "H": 137,
        "MT_weight_kg": 1,
        "Pcs_Boxes_per_LU": 30,
        "Boxes_per_layer": 5,
    },
    "Cardboard XL": {
        "Packaging_Characteristics": "One Way",
        "Cost_per_pcs": 4.46,
        "L": 585,
        "W": 392,
        "H": 282,
        "MT_weight_kg": 1.98,
        "Pcs_Boxes_per_LU": 15,
        "Boxes_per_layer": 5,
    },
    "Cardboard LU (ISO)": {
        "Packaging_Characteristics": "One Way",
        "Cost_per_pcs": 11.17,
        "L": 1180,
        "W": 980,
        "H": 780,
        "MT_weight_kg": 12,
        "Pcs_Boxes_per_LU": 1,
        "Boxes_per_layer": 1,
    },
    "KLT3214 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 6.86,
        "L": 300,
        "W": 200,
        "H": 147,
        "MT_weight_kg": 1.17,
        "Pcs_Boxes_per_LU": 96,
        "Boxes_per_layer": 16,
    },
    "KLT4314 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 11.34,
        "L": 400,
        "W": 300,
        "H": 147,
        "MT_weight_kg": 1.68,
        "Pcs_Boxes_per_LU": 48,
        "Boxes_per_layer": 8,
    },
    "KLT4328 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 12.00,
        "L": 400,
        "W": 300,
        "H": 280,
        "MT_weight_kg": 2.1,
        "Pcs_Boxes_per_LU": 24,
        "Boxes_per_layer": 8,
    },
    "KLT6414 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 18.06,
        "L": 600,
        "W": 400,
        "H": 147,
        "MT_weight_kg": 2.42,
        "Pcs_Boxes_per_LU": 24,
        "Boxes_per_layer": 4,
    },
    "KLT6417 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 18.06,
        "L": 600,
        "W": 400,
        "H": 170,
        "MT_weight_kg": 2.42,
        "Pcs_Boxes_per_LU": 20,
        "Boxes_per_layer": 4,
    },
    "KLT6422 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 18.90,
        "L": 600,
        "W": 400,
        "H": 220,
        "MT_weight_kg": 3.2,
        "Pcs_Boxes_per_LU": 16,
        "Boxes_per_layer": 4,
    },
    "KLT6428 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 19.49,
        "L": 600,
        "W": 400,
        "H": 280,
        "MT_weight_kg": 3.27,
        "Pcs_Boxes_per_LU": 12,
        "Boxes_per_layer": 4,
    },
    "R-KLT6429 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 20.00,
        "L": 600,
        "W": 400,
        "H": 280,
        "MT_weight_kg": 3.27,
        "Pcs_Boxes_per_LU": 12,
        "Boxes_per_layer": 4,
    },
    "ESD KLT3115 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 8.92,
        "L": 300,
        "W": 200,
        "H": 147,
        "MT_weight_kg": 1.17,
        "Pcs_Boxes_per_LU": 96,
        "Boxes_per_layer": 16,
    },
    "ESD KLT4115 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 14.74,
        "L": 400,
        "W": 300,
        "H": 147,
        "MT_weight_kg": 1.68,
        "Pcs_Boxes_per_LU": 48,
        "Boxes_per_layer": 8,
    },
    "ESD KLT4129 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 15.60,
        "L": 400,
        "W": 300,
        "H": 280,
        "MT_weight_kg": 2.1,
        "Pcs_Boxes_per_LU": 24,
        "Boxes_per_layer": 8,
    },
    "ESD KLT 6115 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 23.48,
        "L": 600,
        "W": 400,
        "H": 147,
        "MT_weight_kg": 2.42,
        "Pcs_Boxes_per_LU": 24,
        "Boxes_per_layer": 4,
    },
    "ESD KLT 6122 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 24.57,
        "L": 600,
        "W": 400,
        "H": 220,
        "MT_weight_kg": 3.2,
        "Pcs_Boxes_per_LU": 16,
        "Boxes_per_layer": 4,
    },
    "ESD KLT 6129 / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 25.34,
        "L": 600,
        "W": 400,
        "H": 280,
        "MT_weight_kg": 3.27,
        "Pcs_Boxes_per_LU": 12,
        "Boxes_per_layer": 4,
    },
    "Green Basket / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 15.00,
        "L": 600,
        "W": 400,
        "H": 150,
        "MT_weight_kg": 2.5,
        "Pcs_Boxes_per_LU": 20,
        "Boxes_per_layer": 4,
    },
    "Magnum OPT": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 260.00,
        "L": 1200,
        "W": 800,
        "H": 960,
        "MT_weight_kg": 52,
        "Pcs_Boxes_per_LU": 1,
        "Boxes_per_layer": 1,
    },
    "Wooden Box": {
        "Packaging_Characteristics": "One Way",
        "Cost_per_pcs": 50.00,
        "L": 1200,
        "W": 800,
        "H": 900,
        "MT_weight_kg": 58,
        "Pcs_Boxes_per_LU": 1,
        "Boxes_per_layer": 1,
    },
    "Gitterbox (rental)": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 2.50,
        "L": 1200,
        "W": 800,
        "H": 900,
        "MT_weight_kg": 80,
        "Pcs_Boxes_per_LU": 1,
        "Boxes_per_layer": 1,
    },
    "Gitterbox": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 100.00,
        "L": 1200,
        "W": 800,
        "H": 900,
        "MT_weight_kg": 80,
        "Pcs_Boxes_per_LU": 1,
        "Boxes_per_layer": 1,
    },
    "EURO LU / LID": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 24.50,
        "L": 1200,
        "W": 800,
        "H": 800,
        "MT_weight_kg": 25.58,
        "Pcs_Boxes_per_LU": 1,
        "Boxes_per_layer": 1,
    },    
}

SPECIAL_PACKAGING = {
    "Inlay tray": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 12.00,
        "L": "like KLT/pallet",    # To be resolved at runtime or prompt user
        "W": "like KLT/pallet",
        "H": "like KLT/pallet",
        "MT_weight_kg": 0.5,
        "Pcs_Boxes_per_LU": None,  # Not specified
        "Boxes_per_layer": None,
    },
    "Inlay tray pallet size": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 30.00,
        "L": 1200,
        "W": 800,
        "H": "xxx",              # To be specified
        "MT_weight_kg": 5,
        "Pcs_Boxes_per_LU": None,
        "Boxes_per_layer": None,
    },
    "Standalone tray": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 15.00,
        "L": 600,
        "W": 400,
        "H": "xxx",
        "MT_weight_kg": 0.6,
        "Pcs_Boxes_per_LU": "xxx",
        "Boxes_per_layer": "xxx",
    },
}


ADDITIONAL_PACKAGING = {
    "Pallet": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 50.00,
        "L": 600,
        "W": 400,
        "H": 100,
        "MT_weight_kg": 5,
        "Pcs_Boxes_per_LU": 4,
        "Boxes_per_layer": 1,
    },
    "Cover": {
        "Packaging_Characteristics": "Returnable",
        "Cost_per_pcs": 30.00,
        "L": 600,
        "W": 400,
        "H": 20,
        "MT_weight_kg": 0.6,
        "Pcs_Boxes_per_LU": 4,
        "Boxes_per_layer": 1,
    },
}


ACCESSORY_PACKAGING = {  
    "Blister": {
        "No_per_PU": 2,
        "Ave_Price": 5.40,
        "Ave_Weight_kg": 0.21,
        "Packaging_Characteristics": None,
    },
    "Layers": {
        "No_per_PU": 5,
        "Ave_Price": 0.39,
        "Ave_Weight_kg": 0.1,
        "Packaging_Characteristics": None,
    },
    "LIDS KLT": {
        "No_per_PU": 1,
        "Ave_Price": 1.50,
        "Ave_Weight_kg": 0.6,
        "Packaging_Characteristics": None,
    },
    "LIDS Pallet": {
        "No_per_PU": 1,
        "Ave_Price": 29.11,
        "Ave_Weight_kg": 5.58,
        "Packaging_Characteristics": None,
    },
    "ISO Pallet Price": {
        "No_per_PU": 1,
        "Ave_Price": 22.00,
        "Ave_Weight_kg": 20,
        "Packaging_Characteristics": "One Way",
    },
    "EURO Pallet Price": {
        "No_per_PU": 1,
        "Ave_Price": 24.50,
        "Ave_Weight_kg": 20,
        "Packaging_Characteristics": "Returnable",
    },
}
