[connections.my_example_connection]
account       = "RXUIAEK-IM13448"
user          = "MARAWAN.YOUNIS@KNORR-BREMSE.COM"
authenticator = "externalbrowser"
role          = "PROD_CVS_LOGISTIC_PLANNING_ALD_DATA_ANALYST"
warehouse     = "PUBLIC_WH"
database      = "PROD"
schema        = "INFORMATION_SCHEMA"
